/**
 * Configuration version of all build dependencies
 */
object BuildDependenciesVersions {
    const val KOTLIN = "1.8.0"
    const val APPCOMPAT = "1.2.0"
    const val MATERIAL = "1.2.1"
    const val COROUTINES = "1.3.9"
    const val ROOM = "2.5.0"
    const val RECYCLE_VIEW = "1.1.0"
    const val NAVIGATION = "2.5.0"
    const val LIFECYCLE_EXT = "2.2.0"
    const val LIFECYCLE = "2.5.1"
    const val CORE_KTX = "1.3.2"
    const val FRAGMENT_KTX = "1.2.5"
    const val CONSTRAIN_LAYOUT = "2.0.2"
    const val SWIPE_REFRESH_LAYOUT = "1.1.0"
    const val PAGING = "2.1.2"
    const val DAGGER = "2.40"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.9.0"
    const val LOGGING = "4.9.0"
    const val MOSHI = "1.11.0"
    const val MOSHI_RETROFIT = "2.6.0"
    const val COIL = "0.13.0"
    const val PLAY_CORE = "1.8.2"
    const val GUAVA = "27.0.1-android"
    const val ZXING = "3.2.1"
    const val ZXING_ANDROID_EMBEDDED = "3.3.0"
    const val GSON = "2.8.6"
    const val ARROW = "1.1.3"
    const val LEAKCANARY = "2.8.1"
    const val DATABINDING = "3.1.4"
    const val CORE_DATA = "2.0.0@aar"
    const val CORE_DATA_COMMONS = "2.0.0"
    const val CORE_DATA_NETWORK = "2.0.0@aar"
    const val CORE_DATA_NETWORK_COMMONS = "1.0.0-alpha2"
    const val CORE_DATA_NETWORK_TEST = "1.1.1@aar"
    const val CORE_DOMAIN = "1.0.0"
    const val CORE_NAVIGATION = "1.0.0:beta01@aar"
    const val CORE_VIEWMODEL = "1.0.0:beta01@aar"
    const val DNIEDROID = "2.3.111@aar"
    const val FABRIC_SDK = "2.2.7"

    // Tests
    const val TEST = "1.4.0"
    const val EXT = "1.1.2"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13"
    const val ROBOELECTRIC = "4.4"
    const val MOCKK = "1.10.2"
    const val ASSERTJ = "3.17.2"
    const val ESPRESSO = "3.4.0"
    const val FRAGMENT_TEST = "1.2.5"
    const val MOCK_WEB_SERVER = "4.9.0"
}
